// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgd80i_tD_GIZ2WPF6heaH1Ej5uqJtogQ',
    appId: '1:232374549042:web:02e0b5f454636bcf561a2b',
    messagingSenderId: '232374549042',
    projectId: 'evacuaid-76074',
    authDomain: 'evacuaid-76074.firebaseapp.com',
    storageBucket: 'evacuaid-76074.firebasestorage.app',
    measurementId: 'G-MBFB5S9FJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4BsBRUgq6GOuJRAz3E_9-5KQ8Soqyfg',
    appId: '1:232374549042:android:000855b9f8d3709d561a2b',
    messagingSenderId: '232374549042',
    projectId: 'evacuaid-76074',
    storageBucket: 'evacuaid-76074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgh3qMsT7uee-bvZ_RqSYly0xhm6b1gVI',
    appId: '1:232374549042:ios:a6422b37c85c1ea9561a2b',
    messagingSenderId: '232374549042',
    projectId: 'evacuaid-76074',
    storageBucket: 'evacuaid-76074.firebasestorage.app',
    iosBundleId: 'com.example.evacuaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgh3qMsT7uee-bvZ_RqSYly0xhm6b1gVI',
    appId: '1:232374549042:ios:a6422b37c85c1ea9561a2b',
    messagingSenderId: '232374549042',
    projectId: 'evacuaid-76074',
    storageBucket: 'evacuaid-76074.firebasestorage.app',
    iosBundleId: 'com.example.evacuaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgd80i_tD_GIZ2WPF6heaH1Ej5uqJtogQ',
    appId: '1:232374549042:web:a023bacec1f28df4561a2b',
    messagingSenderId: '232374549042',
    projectId: 'evacuaid-76074',
    authDomain: 'evacuaid-76074.firebaseapp.com',
    storageBucket: 'evacuaid-76074.firebasestorage.app',
    measurementId: 'G-317WDNZD94',
  );
}
